### PR TITLE
Master

### PR DESCRIPTION
**Pull request by tabarra**
Few minor edits. Please check commits for details.

### CODE REVIEW

**Comment by ZDi-it** [comment]
Hi Tabarra! Thanks. Did you try this with PHP5.3? I know it's not supported anymore, but I added the pwdcrypt.php to fill the gap, since many shared hostings still offer this dinosaur version as default.

I'll check the code tomorrow morning!
Thank you

**Comment by tabarra** [comment]
No, sorry, only on php 5.6. IMHO you should discard this file.

**Comment by tabarra** [comment]
The db.php is called from inside the db.php

**Comment by ZDi-it** [comment]
You removed all inclusions in commit e28607eed2af75794db52c31a08a094c4263dbc6

**Comment by tabarra** [comment]
https://github.com/ZDi-it/PHPurl/commit/e28607eed2af75794db52c31a08a094c4263dbc6#diff-62cd37e1a5d3bd9526c1c25c67c1a536R24

**Comment by tabarra** [comment]
Everything ok?

**Comment by ZDi-it** [comment]
Been super busy! This weekend I'm going to working the project and merge you.
Thanks!

**Comment by tabarra** [comment]
BTW, there's a huge SQL injection vulnerability at go.php:12.  
It was actually already there, the line was modified only because my editor removed the space at the end before \n.

**Comment by eolix** [comment]
HI @tabarra . What is the SQL injection vulnerability you mentioned?

**Comment by tabarra** [comment]
Basically the entire `go.php`, since you don't filter the `$_GET['id']` at any point.  
You could use prepared statements there, but at least you should test the variable using [ctype_digit()](http://php.net/manual/en/function.ctype-digit.php).

**Pull request merged**
